### ISSUE TITLE
Seattle downloadable data

### ISSUE THREAD

**Issue by Ennazus** [psrc/travel-study-stories#41]
For “Seattle households only”, is it possible to make an indication of Seattle households subset in the name of the downloadable table?

**Comment by cyyllam** [comment]
@Ennazus  It's in the filename, but I can add it to ... maybe the first column header?

it looks like I need to update the metadata page to reference 2017-19 (instead of just 2017) data as well. Should I copy it from somewhere or just replace the years to make it relevant?

**Comment by cyyllam** [comment]
Downloaded data edits to do:

- change filename `HHSurvey2017-19`
- update `About` tab in excel workbook to reflect `2017-19`

**Comment by cyyllam** [comment]
@Ennazus added an extra column to the the tables in the downloaded files that indicates the result type aka `Regional Results` or `Seattle Results`
